version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gocritic
    - gosec
    - unconvert
    - dupl
    - goconst
    - misspell
  settings:
    gocritic:
      disabled-checks:
        - ifElseChain
        - wrapperFunc
    revive:
      rules:
        - name: unused-parameter
          severity: warning
  exclusions:
    rules:
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - goconst
          - dupl
          - errcheck
          - revive

formatters:
  enable:
    - gofmt
    - goimports
