run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive
    - gocritic
    - gofmt
    - goimports
    - gosec
    - unconvert
    - dupl
    - goconst
    - misspell

linters-settings:
  gocritic:
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  revive:
    rules:
      - name: unused-parameter
        severity: warning

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - dupl
        - errcheck
    - path: internal/migrate/mock\.go
      linters:
        - dupl
        - errcheck
        - revive