before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    binary: git-mfpr
    main: ./cmd/git-mfpr
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

brews:
  - name: git-mfpr
    homepage: "https://github.com/user/git-mfpr"
    description: "Migrate GitHub pull requests from forks to branches"
    repository:
      owner: user
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    folder: Formula
    test: |
      system "#{bin}/git-mfpr", "--help"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  draft: false
  prerelease: false
  name_template: '{{ .ProjectName }} {{ .Version }}'
  extra_files:
    - glob: ./dist/*.tar.gz
    - glob: ./dist/*.zip

# Snapshot configuration for RC builds
snapshot:
  name_template: "{{ incpatch .Version }}-next"

# Docker configuration (optional)
dockers:
  - image_templates:
      - "ghcr.io/user/git-mfpr:{{ .Version }}"
      - "ghcr.io/user/git-mfpr:latest"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--platform=linux/arm64" 